services:
  # ================================
  #            MONGODB
  # ================================
  mongo-apple:
    image: mongo:4.4.6
    container_name: mongo-apple
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-apple:/data/db
    restart: always

  mongo-fitbit:
    image: mongo:4.4.6
    container_name: mongo-fitbit
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo-fitbit:/data/db
    restart: always

  # ================================
  #            INFLUXDB
  # ================================
  influx-apple:
    image: influxdb:1.8.4
    container_name: influx-apple
    environment:
      INFLUXDB_DB: applewatch
    ports:
      - "8086:8086"
    volumes:
      - ./data/influx-apple:/var/lib/influxdb
    restart: always

  influx-fitbit:
    image: influxdb:1.8.4
    container_name: influx-fitbit
    environment:
      INFLUXDB_DB: fitbit
    ports:
      - "8087:8086"
    volumes:
      - ./data/influx-fitbit:/var/lib/influxdb
    restart: always

  # ================================
  #             GRAFANA
  # ================================
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    user: "472:0"     # usu√°rio interno do grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: always

  # ================================
  #              AIRFLOW
  # ================================
  airflow-db:
    image: postgres:13
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./airflow/db:/var/lib/postgresql/data
    networks:
      - data-analytics-net
    restart: always

  airflow-init:
    image: apache/airflow:2.8.0
    container_name: airflow-init
    depends_on:
      - airflow-db
    env_file:
      - ./common.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    user: "50000:0"
    entrypoint: /bin/bash
    command: -c "
      airflow db migrate &&
      airflow users create \
        --username admin \
        --password admin \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email admin@example.com || true
      "
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    networks:
      - data-analytics-net
    restart: "no"

  airflow-webserver:
    image: apache/airflow:2.8.0
    container_name: airflow-webserver
    depends_on:
      - airflow-db
    env_file:
      - ./common.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__WEBSERVER__WORKERS: 4
    user: "50000:0"
    command: webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    networks:
      - data-analytics-net
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.8.0
    container_name: airflow-scheduler
    depends_on:
      - airflow-db
    env_file:
      - ./common.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    user: "50000:0"
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    networks:
      - data-analytics-net
    restart: always

networks:
  data-analytics-net:
    driver: bridge
