services:
  # ================================
  #            MONGODB
  # ================================
  mongo-apple:
    image: mongo:4.4.6
    container_name: mongo-apple
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-apple:/data/db
    restart: always

  mongo-fitbit:
    image: mongo:4.4.6
    container_name: mongo-fitbit
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo-fitbit:/data/db
    restart: always

  # ================================
  #            INFLUXDB
  # ================================
  influx-apple:
    image: influxdb:1.8.4
    container_name: influx-apple
    environment:
      INFLUXDB_DB: applewatch
    ports:
      - "8086:8086"
    volumes:
      - ./data/influx-apple:/var/lib/influxdb
    restart: always

  influx-fitbit:
    image: influxdb:1.8.4
    container_name: influx-fitbit
    environment:
      INFLUXDB_DB: fitbit
    ports:
      - "8087:8086"
    volumes:
      - ./data/influx-fitbit:/var/lib/influxdb
    restart: always

  # ================================
  #             GRAFANA
  # ================================
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    user: "472:0"     # usuÃ¡rio interno do grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: always

  # ================================
  #              AIRFLOW
  # ================================
  airflow:
    image: apache/airflow:2.8.0
    container_name: airflow
    user: "${AIRFLOW_UID:-50000}:0"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/airflow.db"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
        airflow webserver &
        airflow scheduler
      "
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/airflow.db:/opt/airflow/airflow.db
    restart: always

networks:
  default:
    name: data-analytics-net
